version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: ocean-DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${OCEAN_ROOT_PASSWORD}
      MYSQL_USER: ${OCEAN_USER}
      MYSQL_PASSWORD: ${OCEAN_DB_USER_PASSWORD}
      MYSQL_DATABASE: ${OCEAN_DB}
    ports:
      - "${OCEAN_DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake

  api:
    build: .
    container_name: ocean-api-server
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      OCEAN_DB_PORT: ${OCEAN_DB_PORT}
      OCEAN_DB: ${OCEAN_DB}
      OCEAN_DB_HOST: ${OCEAN_DB_HOST}
      OCEAN_USER: ${OCEAN_USER}
      OCEAN_DB_USER_PASSWORD: ${OCEAN_DB_USER_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # 데이터베이스 초기화 시간을 확보하기 위해 10초 대기 후 API 서버 실행
    command: >
      sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  db-data:
